package com.eitax.recall.front.domain;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

import lombok.Data;

@Data
@DynamoDBTable(tableName="profile")
public class Profile {
	@DynamoDBAutoGeneratedKey
	@DynamoDBHashKey(attributeName = "profile_id")
	private String profileId;
	@DynamoDBAttribute(attributeName="profile_name") 
	private String profileName;
	@DynamoDBAttribute(attributeName="access_key") 
	private String accessKey;
	@DynamoDBAttribute(attributeName="secret_key") 
	private String secretKey;
	@DynamoDBAttribute(attributeName="aws_id") 
	private String awsId;
	@DynamoDBAttribute(attributeName="region") 
	private String region;
	@DynamoDBAttribute(attributeName="email") 
	private String email;
	@DynamoDBAttribute(attributeName="role") 
	private String role;
	
}
