spring:
 datasource:
 driverClassName: org.h2.Driver
 url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
 username: sa
 password:
 
spring.jpa.show-sql: true
spring.thymeleaf.cache: false
server.port: 10080

logging.level.: INFO
logging.level.root: INFO
logging.level.ROOT: INFO

#logging:
#    file: logs/myapp.log
#    level:
#        org.springframework.security.ldap.authentication: DEBUG
#        org.springframework.security.ldap.authentication.ad.ActiveDirectoryLdapAuthenticationProvider: DEBUG

server:
 contextPath: /cloud-tool
 session-timeout: 9000
